name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        | 
        PATH=pwd
        docker build . --tag --file $PATH/DockerFile nginx:$(date +%s)
